import sys


class MovieRecommender:
    def __init__(self):
        self.movies = {}  # Dictionary to store movie information
        self.genres = {1: "Action", 2: "Comedy", 3: "Documentary", 4: "Drama", 5: "Family", 6: "Fantasy", 7: "Horror",
                       8: "Sci-Fi", 9: "Romance", 10: "Thriller"}  # Genre mapping
        self.populate_movies()  # Initialize the movies dictionary with some predefined movies

    def add_movie(self, title, genre, initial_rating):
        # Add a new movie with its initial rating to the movies dictionary
        if title not in self.movies:
            self.movies[title] = {'genre': genre, 'ratings': [initial_rating]}
        else:
            self.movies[title]['ratings'].append(initial_rating)

    def rate_movie(self, title, genre, rating):
        # Rate an existing movie or add it to the database if it doesn't exist
        if title in self.movies:
            self.movies[title]['ratings'].append(rating)
            print(f"Rating '{rating}' added for movie '{title}'.")
        else:
            self.add_movie(title, genre, rating)
            print(f"Movie '{title}' added to the database with rating '{rating}'.")

    def get_average_rating(self, title):
        # Calculate and return the average rating for a given movie
        if title in self.movies:
            ratings = self.movies[title]['ratings']
            return sum(ratings) / len(ratings)
        return 0

    def get_recommendations(self, genre, rating):
        # Recommend movies based on genre and a specific rating
        recommended_movies = []
        for title, info in self.movies.items():
            if info['genre'].lower() == genre.lower() and self.get_average_rating(title) == rating:
                recommended_movies.append(title)
        return recommended_movies

    def populate_movies(self):
        movies = {
            # Action movies
            "Mad Max: Fury Road (2015)": {"genre": "Action", "ratings": [5]},
            "Lakshya (2004)": {"genre": "Action", "ratings": [5]},
            "Uri: The Surgical Strike (2019)": {"genre": "Action", "ratings": [5]},
            "The Terminator (1984)": {"genre": "Action", "ratings": [5]},
            "Die Hard (1988)": {"genre": "Action", "ratings": [5]},
            "Gladiator (2000)": {"genre": "Action", "ratings": [5]},
            "Baahubali 2: The Conclusion (2017)": {"genre": "Action", "ratings": [5]},
            "Dhoom 2 (2006)": {"genre": "Action", "ratings": [5]},
            "War (2019)": {"genre": "Action", "ratings": [5]},
            "KGF: Chapter 1 (2018)": {"genre": "Action", "ratings": [5]},
            "Vishwaroopam (2013)": {"genre": "Action", "ratings": [5]},
            "Léon: The Professional (1994)": {"genre": "Action", "ratings": [4]},
            "John Wick (2014)": {"genre": "Action", "ratings": [4]},
            "The Matrix (1999)": {"genre": "Action", "ratings": [4]},
            "Mission: Impossible - Fallout (2018)": {"genre": "Action", "ratings": [4]},
            "The Bourne Identity (2002)": {"genre": "Action", "ratings": [4]},
            "Dhoom (2004)": {"genre": "Action", "ratings": [4]},
            "Bang Bang! (2014)": {"genre": "Action", "ratings": [4]},
            "Robot (2010)": {"genre": "Action", "ratings": [4]},
            "Commando (2013)": {"genre": "Action", "ratings": [4]},
            "War (2019)": {"genre": "Action", "ratings": [4]},
            "The Expendables (2010)": {"genre": "Action", "ratings": [3]},
            "Tomb Raider (2018)": {"genre": "Action", "ratings": [3]},
            "Battleship (2012)": {"genre": "Action", "ratings": [3]},
            "G.I. Joe: The Rise of Cobra (2009)": {"genre": "Action", "ratings": [3]},
            "Brothers (2015)": {"genre": "Action", "ratings": [3]},
            "Force (2011)": {"genre": "Action", "ratings": [3]},
            "Tevar (2015)": {"genre": "Action", "ratings": [3]},
            "Dishoom (2016)": {"genre": "Action", "ratings": [3]},
            "Race 2 (2013)": {"genre": "Action", "ratings": [3]},
            "Speed 2: Cruise Control (1997)": {"genre": "Action", "ratings": [2]},
            "A Good Day to Die Hard (2013)": {"genre": "Action", "ratings": [2]},
            "Battlefield Earth (2000)": {"genre": "Action", "ratings": [2]},
            "Catwoman (2004)": {"genre": "Action", "ratings": [2]},
            "The Last Airbender (2010)": {"genre": "Action", "ratings": [2]},
            "Himmatwala (2013)": {"genre": "Action", "ratings": [2]},
            "Joker (2012)": {"genre": "Action", "ratings": [2]},
            "Kites (2010)": {"genre": "Action", "ratings": [2]},
            "Himmat (1996)": {"genre": "Action", "ratings": [2]},
            "Ballistic: Ecks vs. Sever (2002)": {"genre": "Action", "ratings": [1]},
            "Alone in the Dark (2005)": {"genre": "Action", "ratings": [1]},
            "Gigli (2003)": {"genre": "Action", "ratings": [1]},
            "Superbabies: Baby Geniuses 2 (2004)": {"genre": "Action", "ratings": [1]},
            "Catwoman (2004)": {"genre": "Action", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Action", "ratings": [1]},
            "Prince (2010)": {"genre": "Action", "ratings": [1]},
            "Chandni Chowk to China (2009)": {"genre": "Action", "ratings": [1]},

            # Comedy movies
            "Groundhog Day (1993)": {"genre": "Comedy", "ratings": [5]},
            "The Grand Budapest Hotel (2014)": {"genre": "Comedy", "ratings": [5]},
            "Monty Python and the Holy Grail (1975)": {"genre": "Comedy", "ratings": [5]},
            "Superbad (2007)": {"genre": "Comedy", "ratings": [5]},
            "Anchorman: The Legend of Ron Burgundy (2004)": {"genre": "Comedy", "ratings": [5]},
            "Hera Pheri (2000)": {"genre": "Comedy", "ratings": [5]},
            "Munna Bhai M.B.B.S. (2003)": {"genre": "Comedy", "ratings": [5]},
            "Golmaal:Fun Unlimited (2006)": {"genre": "Comedy", "ratings": [5]},
            "Chupke Chupke (1975)": {"genre": "Comedy", "ratings": [5]},
            "Ferris Bueller's Day Off (1986)": {"genre": "Comedy", "ratings": [4]},
            "The Hangover (2009)": {"genre": "Comedy", "ratings": [4]},
            "Napoleon Dynamite (2004)": {"genre": "Comedy", "ratings": [4]},
            "Mean Girls (2004)": {"genre": "Comedy", "ratings": [4]},
            "Dumb and Dumber (1994)": {"genre": "Comedy", "ratings": [4]},
            "Welcome (2007)": {"genre": "Comedy", "ratings": [4]},
            "Lage Raho Munna Bhai (2006)": {"genre": "Comedy", "ratings": [4]},
            "Entertainment (2014)": {"genre": "Comedy", "ratings": [4]},
            "Queen (2013)": {"genre": "Comedy", "ratings": [4]},
            "Vicky Donor (2012)": {"genre": "Comedy", "ratings": [4]},
            "Step Brothers (2008)": {"genre": "Comedy", "ratings": [3]},
            "Hot Tub Time Machine (2010)": {"genre": "Comedy", "ratings": [3]},
            "Zoolander (2001)": {"genre": "Comedy", "ratings": [3]},
            "Tropic Thunder (2008)": {"genre": "Comedy", "ratings": [3]},
            "Get Him to the Greek (2010)": {"genre": "Comedy", "ratings": [3]},
            "Housefull (2010)": {"genre": "Comedy", "ratings": [3]},
            "Golmaal: Fun Unlimited (2006)": {"genre": "Comedy", "ratings": [3]},
            "Dhamaal (2007)": {"genre": "Comedy", "ratings": [3]},
            "Bol Bachchan (2012)": {"genre": "Comedy", "ratings": [3]},
            "Total Dhamaal (2019)": {"genre": "Comedy", "ratings": [3]},
            "Norbit (2007)": {"genre": "Comedy", "ratings": [2]},
            "Jack and Jill (2011)": {"genre": "Comedy", "ratings": [2]},
            "Movie 43 (2013)": {"genre": "Comedy", "ratings": [2]},
            "Gigli (2003)": {"genre": "Comedy", "ratings": [2]},
            "The Love Guru (2008)": {"genre": "Comedy", "ratings": [2]},
            "Humshakals (2014)": {"genre": "Comedy", "ratings": [2]},
            "Joker (2012)": {"genre": "Comedy", "ratings": [2]},
            "Yamla Pagla Deewana 2 (2013)": {"genre": "Comedy", "ratings": [2]},
            "Disaster Movie (2008)": {"genre": "Comedy", "ratings": [1]},
            "Epic Movie (2007)": {"genre": "Comedy", "ratings": [1]},
            "Meet the Spartans (2008)": {"genre": "Comedy", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Comedy", "ratings": [1]},
            "Joker (2012)": {"genre": "Comedy", "ratings": [1]},
            "Kyaa Super Kool Hain Hum (2012)": {"genre": "Comedy", "ratings": [1]},
            "Great Grand Masti (2016)": {"genre": "Comedy", "ratings": [1]},

            # Documentary movies
            "13th (2016)": {"genre": "Documentary", "ratings": [5]},
            "Free Solo (2018)": {"genre": "Documentary", "ratings": [5]},
            "The Kashmir Files (2022)": {"genre": "Documentary", "ratings": [5]},
            "The Vaccine War (2023)": {"genre": "Documentary", "ratings": [5]},
            "Article 370 (2024)": {"genre": "Documentary", "ratings": [5]},
            "Sachin: A Billion Dreams (2017)": {"genre": "Documentary", "ratings": [4]},
            "Won't You Be My Neighbor? (2018)": {"genre": "Documentary", "ratings": [5]},
            "Jiro Dreams of Sushi (2011)": {"genre": "Documentary", "ratings": [5]},
            "Man on Wire (2008)": {"genre": "Documentary", "ratings": [5]},
            "The Act of Killing (2012)": {"genre": "Documentary", "ratings": [5]},
            "Amy (2015)": {"genre": "Documentary", "ratings": [5]},
            "The Cove (2009)": {"genre": "Documentary", "ratings": [5]},
            "Searching for Sugar Man (2012)": {"genre": "Documentary", "ratings": [5]},
            "Blackfish (2013)": {"genre": "Documentary", "ratings": [5]},
            "Grizzly Man (2005)": {"genre": "Documentary", "ratings": [4]},
            "Oppenheimer (2023)": {"genre": "Documentary", "ratings": [4]},
            "The Fog of War (2003)": {"genre": "Documentary", "ratings": [4]},
            "Exit Through the Gift Shop (2010)": {"genre": "Documentary", "ratings": [4]},
            "Life Itself (2014)": {"genre": "Documentary", "ratings": [4]},
            "An Inconvenient Truth (2006)": {"genre": "Documentary", "ratings": [4]},
            "March of the Penguins (2005)": {"genre": "Documentary", "ratings": [4]},
            "Fahrenheit 9/11 (2004)": {"genre": "Documentary", "ratings": [4]},
            "Citizenfour (2014)": {"genre": "Documentary", "ratings": [4]},
            "The Social Dilemma (2020)": {"genre": "Documentary", "ratings": [4]},
            "Bowling for Columbine (2002)": {"genre": "Documentary", "ratings": [4]},
            "Supersize Me (2004)": {"genre": "Documentary", "ratings": [3]},
            "Waiting for 'Superman' (2010)": {"genre": "Documentary", "ratings": [3]},
            "Food, Inc. (2008)": {"genre": "Documentary", "ratings": [3]},
            "Shabaash Mithu (2022)": {"genre": "Documentary", "ratings": [3]},
            "The King of Kong: A Fistful of Quarters (2007)": {"genre": "Documentary", "ratings": [3]},
            "This Is Spinal Tap (1984)": {"genre": "Documentary", "ratings": [3]},
            "Icarus (2017)": {"genre": "Documentary", "ratings": [3]},
            "Gasland (2010)": {"genre": "Documentary", "ratings": [3]},
            "Enron: The Smartest Guys in the Room (2005)": {"genre": "Documentary", "ratings": [3]},
            "Inside Job (2010)": {"genre": "Documentary", "ratings": [3]},
            "13th (2016)": {"genre": "Documentary", "ratings": [3]},
            "Expelled: No Intelligence Allowed (2008)": {"genre": "Documentary", "ratings": [2]},
            "The Bridge (2006)": {"genre": "Documentary", "ratings": [2]},
            "An Inconvenient Sequel: Truth to Power (2017)": {"genre": "Documentary", "ratings": [2]},
            "The Wolfpack (2015)": {"genre": "Documentary", "ratings": [2]},
            "Catfish (2010)": {"genre": "Documentary", "ratings": [2]},
            "Jesus Camp (2006)": {"genre": "Documentary", "ratings": [2]},
            "Sicko (2007)": {"genre": "Documentary", "ratings": [2]},
            "The Queen of Versailles (2012)": {"genre": "Documentary", "ratings": [2]},
            "Kurt & Courtney (1998)": {"genre": "Documentary", "ratings": [2]},
            "The Secret (2006)": {"genre": "Documentary", "ratings": [2]},
            "Boys Beware (1961)": {"genre": "Documentary", "ratings": [1]},
            "Expelled: No Intelligence Allowed (2008)": {"genre": "Documentary", "ratings": [1]},
            "Kony 2012 (2012)": {"genre": "Documentary", "ratings": [1]},
            "Loose Change (2005)": {"genre": "Documentary", "ratings": [1]},
            "The Principle (2014)": {"genre": "Documentary", "ratings": [1]},
            "Blackfish (2013)": {"genre": "Documentary", "ratings": [1]},
            "The Act of Killing (2012)": {"genre": "Documentary", "ratings": [1]},
            "What the Bleep Do We Know!? (2004)": {"genre": "Documentary", "ratings": [1]},
            "Food, Inc. (2008)": {"genre": "Documentary", "ratings": [1]},
            "Supersize Me (2004)": {"genre": "Documentary", "ratings": [1]},

            # Drama movies
            "The Shawshank Redemption (1994)": {"genre": "Drama", "ratings": [5]},
            "Forrest Gump (1994)": {"genre": "Drama", "ratings": [5]},
            "Ford v Ferrari (2019)": {"genre": "Drama", "ratings": [5]},
            "Schindler's List (1993)": {"genre": "Drama", "ratings": [5]},
            "The Godfather (1972)": {"genre": "Drama", "ratings": [5]},
            "12 Years a Slave (2013)": {"genre": "Drama", "ratings": [5]},
            "Mary Kom (2014)": {"genre": "Drama", "ratings": [5]},
            "12th Fail (2023)": {"genre": "Drama", "ratings": [5]},
            "Shershah (2021)": {"genre": "Drama", "ratings": [5]},
            "Mission Mangal (2019)": {"genre": "Drama", "ratings": [5]},
            "M.S. Dhoni: The Untold Story (2016)": {"genre": "Drama", "ratings": [5]},
            "Padmaavat (2018)": {"genre": "Drama", "ratings": [5]},
            "Bajirao Mastani (2015)": {"genre": "Drama", "ratings": [5]},
            "Pather Panchali (1955)": {"genre": "Drama", "ratings": [5]},
            "A Beautiful Mind (2001)": {"genre": "Drama", "ratings": [4]},
            "Student Of The Year (2013)": {"genre": "Drama", "ratings": [4]},
            "Good Will Hunting (1997)": {"genre": "Drama", "ratings": [4]},
            "The Pursuit of Happyness (2006)": {"genre": "Drama", "ratings": [4]},
            "The Green Mile (1999)": {"genre": "Drama", "ratings": [4]},
            "Dead Poets Society (1989)": {"genre": "Drama", "ratings": [4]},
            "Pink (2016)": {"genre": "Drama", "ratings": [4]},
            "Barfi! (2012)": {"genre": "Drama", "ratings": [4]},
            "Zindagi Na Milegi Dobara (2011)": {"genre": "Drama", "ratings": [5]},
            "The Blind Side (2009)": {"genre": "Drama", "ratings": [3]},
            "Slumdog Millionaire (2008)": {"genre": "Drama", "ratings": [3]},
            "The Social Network (2010)": {"genre": "Drama", "ratings": [3]},
            "The Help (2011)": {"genre": "Drama", "ratings": [3]},
            "Lion (2016)": {"genre": "Drama", "ratings": [3]},
            "Queen (2013)": {"genre": "Drama", "ratings": [3]},
            "Udaan (2010)": {"genre": "Drama", "ratings": [3]},
            "Masaan (2015)": {"genre": "Drama", "ratings": [3]},
            "Gully Boy (2019)": {"genre": "Drama", "ratings": [3]},
            "The Great Gatsby (2013)": {"genre": "Drama", "ratings": [2]},
            "Revolutionary Road (2008)": {"genre": "Drama", "ratings": [2]},
            "The Last Song (2010)": {"genre": "Drama", "ratings": [2]},
            "The Twilight Saga: Breaking Dawn – Part 1 (2011)": {"genre": "Drama", "ratings": [2]},
            "Kalank (2019)": {"genre": "Drama", "ratings": [2]},
            "Shaandaar (2015)": {"genre": "Drama", "ratings": [2]},
            "Raabta (2017)": {"genre": "Drama", "ratings": [2]},
            "Befikre (2016)": {"genre": "Drama", "ratings": [2]},
            "Gigli (2003)": {"genre": "Drama", "ratings": [1]},
            "Glitter (2001)": {"genre": "Drama", "ratings": [1]},
            "Swept Away (2002)": {"genre": "Drama", "ratings": [1]},
            "The Room (2003)": {"genre": "Drama", "ratings": [1]},
            "Catwoman (2004)": {"genre": "Drama", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Drama", "ratings": [1]},
            "Joker (2012)": {"genre": "Drama", "ratings": [1]},
            "Prince (2010)": {"genre": "Drama", "ratings": [1]},
            "Chandni Chowk to China (2009)": {"genre": "Drama", "ratings": [1]},

            # Family movies
            "Ramayana: The Epic (2010)": {"genre": "Family", "ratings": [5]},
            "OMG- Oh My God! (2012)": {"genre": "Family", "ratings": [5]},
            "Mahabharat (2013)": {"genre": "Family", "ratings": [5]},
            "The Lion King (1994)": {"genre": "Family", "ratings": [5]},
            "Toy Story (1995)": {"genre": "Family", "ratings": [5]},
            "Finding Nemo (2003)": {"genre": "Family", "ratings": [5]},
            "Harry Potter and the Sorcerer's Stone (2001)": {"genre": "Family", "ratings": [5]},
            "The Incredibles (2004)": {"genre": "Family", "ratings": [5]},
            "Chhichhore (2019)": {"genre": "Family", "ratings": [5]},
            "Stanley Ka Dabba (2011)": {"genre": "Family", "ratings": [5]},
            "Frozen (2013)": {"genre": "Family", "ratings": [4]},
            "Beauty and the Beast (1991)": {"genre": "Family", "ratings": [4]},
            "Shrek (2001)": {"genre": "Family", "ratings": [4]},
            "Moana (2016)": {"genre": "Family", "ratings": [4]},
            "The Jungle Book (2016)": {"genre": "Family", "ratings": [4]},
            "Piku (2015)": {"genre": "Family", "ratings": [4]},
            "Kapoor & Sons (2016)": {"genre": "Family", "ratings": [4]},
            "Hichki (2018)": {"genre": "Family", "ratings": [4]},
            "English Vinglish (2012)": {"genre": "Family", "ratings": [4]},
            "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (2005)": {"genre": "Family", "ratings": [3]},
            "Madagascar (2005)": {"genre": "Family", "ratings": [3]},
            "Night at the Museum (2006)": {"genre": "Family", "ratings": [3]},
            "Despicable Me (2010)": {"genre": "Family", "ratings": [3]},
            "Bhoothnath (2008)": {"genre": "Family", "ratings": [3]},
            "Koi... Mil Gaya (2003)": {"genre": "Family", "ratings": [3]},
            "Mujhse Dosti Karoge! (2002)": {"genre": "Family", "ratings": [3]},
            "We Are Family (2010)": {"genre": "Family", "ratings": [3]},
            "The Smurfs (2011)": {"genre": "Family", "ratings": [2]},
            "The Flintstones (1994)": {"genre": "Family", "ratings": [2]},
            "Daddy Day Care (2003)": {"genre": "Family", "ratings": [2]},
            "Spy Kids (2001)": {"genre": "Family", "ratings": [2]},
            "Cats & Dogs (2001)": {"genre": "Family", "ratings": [2]},
            "Bachna Ae Haseeno (2008)": {"genre": "Family", "ratings": [2]},
            "Humshakals (2014)": {"genre": "Family", "ratings": [2]},
            "Housefull (2010)": {"genre": "Family", "ratings": [2]},
            "Shaandaar (2015)": {"genre": "Family", "ratings": [2]},
            "Son of the Mask (2005)": {"genre": "Family", "ratings": [1]},
            "Baby Geniuses (1999)": {"genre": "Family", "ratings": [1]},
            "The Cat in the Hat (2003)": {"genre": "Family", "ratings": [1]},
            "Beverly Hills Chihuahua (2008)": {"genre": "Family", "ratings": [1]},
            "Jack and Jill (2011)": {"genre": "Family", "ratings": [1]},
            "Joker (2012)": {"genre": "Family", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Family", "ratings": [1]},
            "Chandni Chowk to China (2009)": {"genre": "Family", "ratings": [1]},
            "Kambakkht Ishq (2009)": {"genre": "Family", "ratings": [1]},

            # Horror Movies
            "The Exorcist (1973)": {"genre": "Horror", "ratings": [5]},
            "The Shining (1980)": {"genre": "Horror", "ratings": [5]},
            "Psycho (1960)": {"genre": "Horror", "ratings": [5]},
            "Get Out (2017)": {"genre": "Horror", "ratings": [5]},
            "A Nightmare on Elm Street (1984)": {"genre": "Horror", "ratings": [5]},
            "Raat (1992)": {"genre": "Horror", "ratings": [5]},
            "Tumbbad (2018)": {"genre": "Horror", "ratings": [5]},
            "Pari (2018)": {"genre": "Horror", "ratings": [5]},
            "Stree (2018)": {"genre": "Horror", "ratings": [5]},
            "Bhool Bhulaiyaa (2007)": {"genre": "Horror", "ratings": [5]},
            "The Conjuring (2013)": {"genre": "Horror", "ratings": [4]},
            "It (2017)": {"genre": "Horror", "ratings": [4]},
            "Hereditary (2018)": {"genre": "Horror", "ratings": [4]},
            "The Ring (2002)": {"genre": "Horror", "ratings": [4]},
            "The Babadook (2014)": {"genre": "Horror", "ratings": [4]},
            "13B: Fear Has a New Address (2009)": {"genre": "Horror", "ratings": [4]},
            "Pizza (2012)": {"genre": "Horror", "ratings": [4]},
            "Raaz (2002)": {"genre": "Horror", "ratings": [4]},
            "Phobia (2016)": {"genre": "Horror", "ratings": [4]},
            "Ek Thi Daayan (2013)": {"genre": "Horror", "ratings": [4]},
            "Insidious (2010)": {"genre": "Horror", "ratings": [3]},
            "Paranormal Activity (2007)": {"genre": "Horror", "ratings": [3]},
            "The Grudge (2004)": {"genre": "Horror", "ratings": [3]},
            "Sinister (2012)": {"genre": "Horror", "ratings": [3]},
            "The Blair Witch Project (1999)": {"genre": "Horror", "ratings": [3]},
            "1920 (2008)": {"genre": "Horror", "ratings": [3]},
            "Shaapit (2010)": {"genre": "Horror", "ratings": [3]},
            "Click (2010)": {"genre": "Horror", "ratings": [3]},
            "Kaal (2005)": {"genre": "Horror", "ratings": [3]},
            "Veerana (1988)": {"genre": "Horror", "ratings": [3]},
            "The Nun (2018)": {"genre": "Horror", "ratings": [2]},
            "Annabelle (2014)": {"genre": "Horror", "ratings": [2]},
            "The Boy (2016)": {"genre": "Horror", "ratings": [2]},
            "Mama (2013)": {"genre": "Horror", "ratings": [2]},
            "The Haunting in Connecticut (2009)": {"genre": "Horror", "ratings": [2]},
            "Raaz 3: The Third Dimension (2012)": {"genre": "Horror", "ratings": [2]},
            "Alone (2015)": {"genre": "Horror", "ratings": [2]},
            "Hawa (2003)": {"genre": "Horror", "ratings": [2]},
            "Darling (2007)": {"genre": "Horror", "ratings": [2]},
            "Kuch Toh Hai (2003)": {"genre": "Horror", "ratings": [2]},
            "The Apparition (2012)": {"genre": "Horror", "ratings": [1]},
            "One Missed Call (2008)": {"genre": "Horror", "ratings": [1]},
            "The Gallows (2015)": {"genre": "Horror", "ratings": [1]},
            "The Devil Inside (2012)": {"genre": "Horror", "ratings": [1]},
            "Slender Man (2018)": {"genre": "Horror", "ratings": [1]},
            "Rokkk (2010)": {"genre": "Horror", "ratings": [1]},
            "Haunted – 3D (2011)": {"genre": "Horror", "ratings": [1]},
            "Ghost (2012)": {"genre": "Horror", "ratings": [1]},
            "Aatma (2013)": {"genre": "Horror", "ratings": [1]},
            "Help (2010)": {"genre": "Horror", "ratings": [1]},

            # Sci-Fi

            "Blade Runner (1982)": {"genre": "Sci-Fi", "ratings": [5]},
            "The Matrix (1999)": {"genre": "Sci-Fi", "ratings": [5]},
            "Inception (2010)": {"genre": "Sci-Fi", "ratings": [5]},
            "2001: A Space Odyssey (1968)": {"genre": "Sci-Fi", "ratings": [5]},
            "Star Wars: Episode IV - A New Hope (1977)": {"genre": "Sci-Fi", "ratings": [5]},
            "Robot (2010)": {"genre": "Sci-Fi", "ratings": [5]},
            "PK (2014)": {"genre": "Sci-Fi", "ratings": [5]},
            "Enthiran (2010)": {"genre": "Sci-Fi", "ratings": [5]},
            "Koi... Mil Gaya (2003)": {"genre": "Sci-Fi", "ratings": [5]},
            "Interstellar (2014)": {"genre": "Sci-Fi", "ratings": [5]},
            "The Terminator (1984)": {"genre": "Sci-Fi", "ratings": [4]},
            "Aliens (1986)": {"genre": "Sci-Fi", "ratings": [4]},
            "The Fifth Element (1997)": {"genre": "Sci-Fi", "ratings": [4]},
            "Avatar (2009)": {"genre": "Sci-Fi", "ratings": [4]},
            "Krrish (2006)": {"genre": "Sci-Fi", "ratings": [4]},
            "Raabta (2017)": {"genre": "Sci-Fi", "ratings": [4]},
            "Chandni Chowk to China (2009)": {"genre": "Sci-Fi", "ratings": [4]},
            "Dasavathaaram (2008)": {"genre": "Sci-Fi", "ratings": [4]},
            "A Flying Jatt (2016)": {"genre": "Sci-Fi", "ratings": [4]},
            "Minority Report (2002)": {"genre": "Sci-Fi", "ratings": [3]},
            "District 9 (2009)": {"genre": "Sci-Fi", "ratings": [3]},
            "Edge of Tomorrow (2014)": {"genre": "Sci-Fi", "ratings": [3]},
            "Prometheus (2012)": {"genre": "Sci-Fi", "ratings": [3]},
            "Looper (2012)": {"genre": "Sci-Fi", "ratings": [3]},
            "Krrish 3 (2013)": {"genre": "Sci-Fi", "ratings": [3]},
            "Action Replayy (2010)": {"genre": "Sci-Fi", "ratings": [3]},
            "Time Machine (2016)": {"genre": "Sci-Fi", "ratings": [3]},
            "Carbon (2017)": {"genre": "Sci-Fi", "ratings": [3]},
            "24 (2016)": {"genre": "Sci-Fi", "ratings": [3]},
            "Independence Day: Resurgence (2016)": {"genre": "Sci-Fi", "ratings": [2]},
            "Pacific Rim: Uprising (2018)": {"genre": "Sci-Fi", "ratings": [2]},
            "Transformers: Age of Extinction (2014)": {"genre": "Sci-Fi", "ratings": [4]},
            "Terminator Genisys (2015)": {"genre": "Sci-Fi", "ratings": [2]},
            "Jupiter Ascending (2015)": {"genre": "Sci-Fi", "ratings": [2]},
            "Love Story 2050 (2008)": {"genre": "Sci-Fi", "ratings": [2]},
            "Jaane Hoga Kya (2006)": {"genre": "Sci-Fi", "ratings": [2]},
            "Prince (2010)": {"genre": "Sci-Fi", "ratings": [2]},
            "Joker (2012)": {"genre": "Sci-Fi", "ratings": [2]},
            "Aa Dekhen Zara (2009)": {"genre": "Sci-Fi", "ratings": [2]},
            "Battlefield Earth (2000)": {"genre": "Sci-Fi", "ratings": [1]},
            "The Adventures of Pluto Nash (2002)": {"genre": "Sci-Fi", "ratings": [1]},
            "Supernova (2000)": {"genre": "Sci-Fi", "ratings": [1]},
            "Stealth (2005)": {"genre": "Sci-Fi", "ratings": [1]},
            "The Last Airbender (2010)": {"genre": "Sci-Fi", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Sci-Fi", "ratings": [1]},
            "Kal Kissne Dekha (2009)": {"genre": "Sci-Fi", "ratings": [1]},
            "Cash (2007)": {"genre": "Sci-Fi", "ratings": [1]},
            "Rudraksh (2004)": {"genre": "Sci-Fi", "ratings": [1]},
            "Fun2shh... Dudes in the 10th Century (2003)": {"genre": "Sci-Fi", "ratings": [1]},

            # Romance movies
            "Titanic (1997)": {"genre": "Romance", "ratings": [5]},
            "The Notebook (2004)": {"genre": "Romance", "ratings": [5]},
            "Pride and Prejudice (2005)": {"genre": "Romance", "ratings": [5]},
            "La La Land (2016)": {"genre": "Romance", "ratings": [5]},
            "Casablanca (1942)": {"genre": "Romance", "ratings": [5]},
            "Jab We Met (2007)": {"genre": "Romance", "ratings": [5]},
            "Barfi! (2012)": {"genre": "Romance", "ratings": [5]},
            "Ok Jaanu (2017)": {"genre": "Romance", "ratings": [3]},
            "Aashiqui 2 (2013)": {"genre": "Romance", "ratings": [5]},
            "The Fault in Our Stars (2014)": {"genre": "Romance", "ratings": [4]},
            "A Walk to Remember (2002)": {"genre": "Romance", "ratings": [4]},
            "Silver Linings Playbook (2012)": {"genre": "Romance", "ratings": [4]},
            "500 Days of Summer (2009)": {"genre": "Romance", "ratings": [4]},
            "Notting Hill (1999)": {"genre": "Romance", "ratings": [4]},
            "Yeh Jawaani Hai Deewani (2013)": {"genre": "Romance", "ratings": [4]},
            "Hum Dil De Chuke Sanam (1999)": {"genre": "Romance", "ratings": [4]},
            "Rockstar (2011)": {"genre": "Romance", "ratings": [4]},
            "Lootera (2013)": {"genre": "Romance", "ratings": [4]},
            "Twilight (2008)": {"genre": "Romance", "ratings": [3]},
            "The Vow (2012)": {"genre": "Romance", "ratings": [3]},
            "Dear John (2010)": {"genre": "Romance", "ratings": [3]},
            "Crazy Rich Asians (2018)": {"genre": "Romance", "ratings": [3]},
            "Me Before You (2016)": {"genre": "Romance", "ratings": [3]},
            "Two States (2014)": {"genre": "Romance", "ratings": [3]},
            "Ae Dil Hai Mushkil (2016)": {"genre": "Romance", "ratings": [3]},
            "Saathiya (2002)": {"genre": "Romance", "ratings": [3]},
            "Tamasha (2015)": {"genre": "Romance", "ratings": [3]},
            "The Lucky One (2012)": {"genre": "Romance", "ratings": [2]},
            "The Last Song (2010)": {"genre": "Romance", "ratings": [2]},
            "Endless Love (2014)": {"genre": "Romance", "ratings": [2]},
            "Leap Year (2010)": {"genre": "Romance", "ratings": [2]},
            "Half Girlfriend (2017)": {"genre": "Romance", "ratings": [2]},
            "London Paris New York (2012)": {"genre": "Romance", "ratings": [2]},
            "Jhootha Hi Sahi (2010)": {"genre": "Romance", "ratings": [2]},
            "Love Story (1981)": {"genre": "Romance", "ratings": [1]},
            "Gigli (2003)": {"genre": "Romance", "ratings": [1]},
            "All About Steve (2009)": {"genre": "Romance", "ratings": [1]},
            "The Love Guru (2008)": {"genre": "Romance", "ratings": [1]},
            "Valentine's Day (2010)": {"genre": "Romance", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Romance", "ratings": [1]},
            "Prem Aggan (1998)": {"genre": "Romance", "ratings": [1]},
            "Chandni Chowk to China (2009)": {"genre": "Romance", "ratings": [1]},
            "What's Your Raashee? (2009)": {"genre": "Romance", "ratings": [1]},

            # Thriller movies

            "The Silence of the Lambs (1991)": {"genre": "Thriller", "ratings": [5]},
            "Se7en (1995)": {"genre": "Thriller", "ratings": [5]},
            "Psycho (1960)": {"genre": "Thriller", "ratings": [5]},
            "The Usual Suspects (1995)": {"genre": "Thriller", "ratings": [5]},
            "The Sixth Sense (1999)": {"genre": "Thriller", "ratings": [5]},
            "Kahaani (2012)": {"genre": "Thriller", "ratings": [5]},
            "Drishyam (2015)": {"genre": "Thriller", "ratings": [5]},
            "Andhadhun (2018)": {"genre": "Thriller", "ratings": [5]},
            "Raat (1992)": {"genre": "Thriller", "ratings": [5]},
            "The Shining (1980)": {"genre": "Thriller", "ratings": [4]},
            "The White Tiger (2021)": {"genre": "Thriller", "ratings": [5]},
            "Zodiac (2007)": {"genre": "Thriller", "ratings": [4]},
            "Prisoners (2013)": {"genre": "Thriller", "ratings": [4]},
            "Gone Girl (2014)": {"genre": "Thriller", "ratings": [4]},
            "Memento (2000)": {"genre": "Thriller", "ratings": [4]},
            "Gupt: The Hidden Truth (1997)": {"genre": "Thriller", "ratings": [4]},
            "Talvar (2015)": {"genre": "Thriller", "ratings": [4]},
            "Johnny Gaddaar (2007)": {"genre": "Thriller", "ratings": [4]},
            "Badla (2019)": {"genre": "Thriller", "ratings": [4]},
            "The Girl with the Dragon Tattoo (2011)": {"genre": "Thriller", "ratings": [3]},
            "Kahaani 2 (2016)": {"genre": "Thriller", "ratings": [3]},
            "Raman Raghav 2.0 (2016)": {"genre": "Thriller", "ratings": [3]},
            "Kaun (1999)": {"genre": "Thriller", "ratings": [3]},
            "Kaabil (2017)": {"genre": "Thriller", "ratings": [3]},
            "Manorama Six Feet Under (2007)": {"genre": "Thriller", "ratings": [3]},
            "A Wednesday (2008)": {"genre": "Thriller", "ratings": [3]},
            "Ek Hasina Thi (2004)": {"genre": "Thriller", "ratings": [3]},
            "Pizza (2014)": {"genre": "Thriller", "ratings": [3]},
            "The Ring (2002)": {"genre": "Thriller", "ratings": [2]},
            "1920 (2008)": {"genre": "Thriller", "ratings": [2]},
            "Table No. 21 (2013)": {"genre": "Thriller", "ratings": [2]},
            "Hisss (2010)": {"genre": "Thriller", "ratings": [2]},
            "Ek Villain (2014)": {"genre": "Thriller", "ratings": [2]},
            "Kaun Hai Villain (2017)": {"genre": "Thriller", "ratings": [2]},
            "Phoonk (2008)": {"genre": "Thriller", "ratings": [2]},
            "404: Error Not Found (2011)": {"genre": "Thriller", "ratings": [2]},
            "Bhoot (2003)": {"genre": "Thriller", "ratings": [2]},
            "13B: Fear Has a New Address (2009)": {"genre": "Thriller", "ratings": [2]},
            "Karzzzz (2008)": {"genre": "Thriller", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Thriller", "ratings": [1]},
            "Tezz (2012)": {"genre": "Thriller", "ratings": [1]},
            "Players (2012)": {"genre": "Thriller", "ratings": [1]},
            "Himmatwala (2013)": {"genre": "Thriller", "ratings": [1]},
            "Mausam (2011)": {"genre": "Thriller", "ratings": [1]},
            "Mr. X (2015)": {"genre": "Thriller", "ratings": [1]},

            # Fantasy movies
            "The Lord of the Rings: The Fellowship of the Ring (2001)": {"genre": "Fantasy", "ratings": [5]},
            "Harry Potter and the Deathly Hallows – Part 2 (2011)": {"genre": "Fantasy", "ratings": [5]},
            "Pan's Labyrinth (2006)": {"genre": "Fantasy", "ratings": [5]},
            "Avatar (2009)": {"genre": "Fantasy", "ratings": [5]},
            "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (2005)": {"genre": "Fantasy","ratings": [5]},
            "Baahubali: The Beginning (2015)": {"genre": "Fantasy", "ratings": [5]},
            "Koi... Mil Gaya (2003)": {"genre": "Fantasy", "ratings": [5]},
            "Harry Potter and the Philosopher's Stone (2001)": {"genre": "Fantasy", "ratings": [5]},
            "Mr. India (1987)": {"genre": "Fantasy", "ratings": [5]},
            "Spirited Away (2001)": {"genre": "Fantasy", "ratings": [4]},
            "Harry Potter and the Prisoner of Azkaban (2004)": {"genre": "Fantasy", "ratings": [4]},
            "The Chronicles of Narnia: Prince Caspian (2008)": {"genre": "Fantasy", "ratings": [4]},
            "Fantastic Beasts and Where to Find Them (2016)": {"genre": "Fantasy", "ratings": [4]},
            "The Jungle Book (2016)": {"genre": "Fantasy", "ratings": [4]},
            "Baahubali 2: The Conclusion (2017)": {"genre": "Fantasy", "ratings": [4]},
            "Rudhramadevi (2015)": {"genre": "Fantasy", "ratings": [4]},
            "The Hobbit: An Unexpected Journey (2012)": {"genre": "Fantasy", "ratings": [4]},
            "Enthiran (2010)": {"genre": "Fantasy", "ratings": [4]},
            "Eega (2012)": {"genre": "Fantasy", "ratings": [4]},
            "Harry Potter and the Goblet of Fire (2005)": {"genre": "Fantasy", "ratings": [3]},
            "The Chronicles of Narnia: The Voyage of the Dawn Treader (2010)": {"genre": "Fantasy", "ratings": [3]},
            "Harry Potter and the Chamber of Secrets (2002)": {"genre": "Fantasy", "ratings": [3]},
            "Thor: Ragnarok (2017)": {"genre": "Fantasy", "ratings": [3]},
            "Fantastic Beasts: The Crimes of Grindelwald (2018)": {"genre": "Fantasy", "ratings": [3]},
            "Mirzya (2016)": {"genre": "Fantasy", "ratings": [3]},
            "Mohenjo Daro (2016)": {"genre": "Fantasy", "ratings": [3]},
            "Magadheera (2009)": {"genre": "Fantasy", "ratings": [3]},
            "Jagga Jasoos (2017)": {"genre": "Fantasy", "ratings": [3]},
            "Harry Potter and the Order of the Phoenix (2007)": {"genre": "Fantasy", "ratings": [2]},
            "The Hobbit: The Battle of the Five Armies (2014)": {"genre": "Fantasy", "ratings": [2]},
            "Inkheart (2008)": {"genre": "Fantasy", "ratings": [2]},
            "Pirates of the Caribbean: Dead Men Tell No Tales (2017)": {"genre": "Fantasy", "ratings": [2]},
            "The BFG (2016)": {"genre": "Fantasy", "ratings": [2]},
            "Thor: The Dark World (2013)": {"genre": "Fantasy", "ratings": [2]},
            "Drona (2008)": {"genre": "Fantasy", "ratings": [2]},
            "The Chronicles of Narnia: The Silver Chair (2023)": {"genre": "Fantasy", "ratings": [2]},
            "A Wrinkle in Time (2018)": {"genre": "Fantasy", "ratings": [2]},
            "Himmatwala (2013)": {"genre": "Fantasy", "ratings": [1]},
            "Krrish 3 (2013)": {"genre": "Fantasy", "ratings": [1]},
            "Joker (2012)": {"genre": "Fantasy", "ratings": [1]},
            "Prince (2010)": {"genre": "Fantasy", "ratings": [1]},
            "Kambakkht Ishq (2009)": {"genre": "Fantasy", "ratings": [1]},

        }
        self.movies.update(movies)  # Add the predefined movies to the movies dictionary


def main():
    recommender = MovieRecommender()  # Create an instance of MovieRecommender

    while True:
        print("Movie Recommender System")
        print("1. Rate a Movie")
        print("2. Get Recommendations")
        print("3. Exit")
        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            title = input("Enter the movie title: ")
            genre = input("Enter the movie genre: ")
            rating = int(input("Enter your rating (1-5): "))
            recommender.rate_movie(title, genre, rating)  # Rate the movie provided by the user

        elif choice == '2':
            print("Select a genre:")
            for num, genre in recommender.genres.items():
                print(f"{num}. {genre}")
            genre_choice = int(input("Enter the number of your choice: "))
            genre = recommender.genres.get(genre_choice, None)  # Get the genre based on user choice
            if genre:
                rating = int(input("Enter the rating (1-5) to filter by: "))
                recommendations = recommender.get_recommendations(genre, rating)  # Get movie recommendations
                if recommendations:
                    print("Recommended Movies:")
                    for movie in recommendations:
                        print(f"- {movie}")
                else:
                    print("No movies found with the specified genre and rating.")
            else:
                print("Invalid genre choice.")

        elif choice == '3':
            print("Exiting the Movie Recommender System. Goodbye!")
            sys.exit()  # Exit the program

        else:
            print("Invalid choice. Please enter 1, 2, or 3.")


if __name__ == "__main__":
    main()  # Run the main function if this script is executed
